### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wanglz111** [vcheckzen/XunleiKuainiaoInShell#2]
cat: ./data/cookies: No such file or directory
cat: ./data/cookies: No such file or directory
Action upgrade failed!

**Comment by vcheckzen** [comment]
把依赖装上，测试 `curl https://www.baidu.com` 是否成功，不行就联系我 `base64.decode(UVE6MzMxOTE0OTEw)`

**Comment by vcheckzen** [comment]
另外听说 star 有解决疑难杂症之效，您可以试试（逃）
