### ISSUE TITLE
Padavan固件ssh之后安装依赖，执行kuainiao.sh报错

### ISSUE THREAD

**Issue by syouko** [vcheckzen/XunleiKuainiaoInShell#3]
报错提示：
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Action upgrade failed!

固件是padavan最新的，ssh之后按照你写的安装了依赖。curl 和wget ip都正常现实

**Comment by vcheckzen** [comment]
文件里没有设置区域相关代码，所以不知道为什么报这个错。方便的话加我 [QQ](http://wpa.qq.com/msgrd?v=3&uin=331914910&site=qq&menu=yes) 或者 [TG 群](https://t.me/pubg2333) 远程看一下
